### ISSUE TITLE
[ BUG REPORT ] - Anticheat persistent file

### ISSUE THREAD

**Issue by Ionlylike1kindofcheese** [Just-Natsuki-Team/NatsukiModDev#281]
I downloaded the game for the first time and after playing I closed the game and started the game later again.
But the noment I open up the game I get greeted with a repeating error:

Traceback (most recent call last):
  File "C:\Users\Eigenaar\OneDrive\Bureaublad\DDLC-1.1.1-pc\renpy\execution.py", line 438, in run
    node.execute()
  File "C:\Users\Eigenaar\OneDrive\Bureaublad\DDLC-1.1.1-pc\renpy\ast.py", line 1656, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Eigenaar\OneDrive\Bureaublad\DDLC-1.1.1-pc\renpy\python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Eigenaar\OneDrive\Bureaublad\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/splash.rpy", line 182, in <module>
    if anticheat != persistent.anticheat:
NameError: name 'anticheat' is not defined

Noments before this error started repeating I also got another error but this stopped showing after just one-time.

Traceback (most recent call last):
  File "C:\Users\Eigenaar\OneDrive\Bureaublad\DDLC-1.1.1-pc\renpy\execution.py", line 438, in run
    node.execute()
  File "C:\Users\Eigenaar\OneDrive\Bureaublad\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Eigenaar\OneDrive\Bureaublad\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-ch30.rpy", line 53, in <module>
    and jn_events.select_event()
  File "game/script-events.rpy", line 24, in select_event
    affinity=Natsuki._getAffinityState(),
NameError: global name 'Natsuki' is not defined

I noticed another issue was reported before me about the natsuki variable not being defined and read the comments asking for a persistent file. 1 problem though: The files cannot be supported in this message so I'll try and look if I can upload the files to an seperate repository and put the link in the comments. If it works you'll see the repository link in the comments. Otherwise I will mention it if we have to find another way to resolve the issue

**Comment by Ionlylike1kindofcheese** [comment]
Ok nvm it was a failure. I don't have git downloaded on this computer and if I wanted to download it. I would need to download an IDE which I don't prefer having on my personal computer. Is there an email adress I can send it too?

**Comment by Blizzardsev** [comment]
Hi @Ionlylike1kindofcheese, thanks for raising a ticket with us.

A fix that should resolve this issue is now in progress.
